spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/job_application
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#Actuator Enable all the EndPoints
management.endpoints.web.exposure.include=*

#Enable All the information in Each URl (here for health)

management.endpoint.health.show-details=always

#Add information to show in info end point by default it is empty

info.app.name=JobApplication
info.app.description=Job Built by Prajwal
info.app.version=1.0.0

#Enable info end point

management.info.env.enabled=true

#Enable shutdown end point

management.endpoint.shutdown.enabled=true

#to enable graceful shutdown

server.shutdown=graceful